version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    depends_on:
      - vector-db
    networks:
      - app-network

  vector-db:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - vector-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  vector-data: